package org.biye.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.biye.mymall.db.domain.MymallAftersale;
import org.biye.mymall.db.domain.MymallAftersaleExample;

public interface MymallAftersaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    long countByExample(MymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int deleteByExample(MymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int insert(MymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int insertSelective(MymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    MymallAftersale selectOneByExample(MymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    MymallAftersale selectOneByExampleSelective(@Param("example") MymallAftersaleExample example, @Param("selective") MymallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    List<MymallAftersale> selectByExampleSelective(@Param("example") MymallAftersaleExample example, @Param("selective") MymallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    List<MymallAftersale> selectByExample(MymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    MymallAftersale selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallAftersale.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    MymallAftersale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    MymallAftersale selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallAftersale record, @Param("example") MymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallAftersale record, @Param("example") MymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallAftersale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MymallAftersaleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_aftersale
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}