package org.biye.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.biye.mymall.db.domain.MymallNotice;
import org.biye.mymall.db.domain.MymallNoticeExample;

public interface MymallNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    long countByExample(MymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int deleteByExample(MymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int insert(MymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int insertSelective(MymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    MymallNotice selectOneByExample(MymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    MymallNotice selectOneByExampleSelective(@Param("example") MymallNoticeExample example, @Param("selective") MymallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    List<MymallNotice> selectByExampleSelective(@Param("example") MymallNoticeExample example, @Param("selective") MymallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    List<MymallNotice> selectByExample(MymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    MymallNotice selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallNotice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    MymallNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    MymallNotice selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallNotice record, @Param("example") MymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallNotice record, @Param("example") MymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MymallNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_notice
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}