package org.biye.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.biye.mymall.db.domain.MymallAdmin;
import org.biye.mymall.db.domain.MymallAdminExample;

public interface MymallAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    long countByExample(MymallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int deleteByExample(MymallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int insert(MymallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int insertSelective(MymallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    MymallAdmin selectOneByExample(MymallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    MymallAdmin selectOneByExampleSelective(@Param("example") MymallAdminExample example, @Param("selective") MymallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    List<MymallAdmin> selectByExampleSelective(@Param("example") MymallAdminExample example, @Param("selective") MymallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    List<MymallAdmin> selectByExample(MymallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    MymallAdmin selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallAdmin.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    MymallAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    MymallAdmin selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallAdmin record, @Param("example") MymallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallAdmin record, @Param("example") MymallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MymallAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_admin
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}