package org.biye.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.biye.mymall.db.domain.MymallRole;
import org.biye.mymall.db.domain.MymallRoleExample;

public interface MymallRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    long countByExample(MymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int deleteByExample(MymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int insert(MymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int insertSelective(MymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    MymallRole selectOneByExample(MymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    MymallRole selectOneByExampleSelective(@Param("example") MymallRoleExample example, @Param("selective") MymallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    List<MymallRole> selectByExampleSelective(@Param("example") MymallRoleExample example, @Param("selective") MymallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    List<MymallRole> selectByExample(MymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    MymallRole selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallRole.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    MymallRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    MymallRole selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallRole record, @Param("example") MymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallRole record, @Param("example") MymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MymallRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_role
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}