package org.biye.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.biye.mymall.db.domain.MymallOrder;
import org.biye.mymall.db.domain.MymallOrderExample;

public interface MymallOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    long countByExample(MymallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int deleteByExample(MymallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int insert(MymallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int insertSelective(MymallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    MymallOrder selectOneByExample(MymallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    MymallOrder selectOneByExampleSelective(@Param("example") MymallOrderExample example, @Param("selective") MymallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    List<MymallOrder> selectByExampleSelective(@Param("example") MymallOrderExample example, @Param("selective") MymallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    List<MymallOrder> selectByExample(MymallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    MymallOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallOrder.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    MymallOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    MymallOrder selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallOrder record, @Param("example") MymallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallOrder record, @Param("example") MymallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MymallOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_order
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}