package org.biye.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.biye.mymall.db.domain.MymallIssue;
import org.biye.mymall.db.domain.MymallIssueExample;

public interface MymallIssueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    long countByExample(MymallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int deleteByExample(MymallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int insert(MymallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int insertSelective(MymallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    MymallIssue selectOneByExample(MymallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    MymallIssue selectOneByExampleSelective(@Param("example") MymallIssueExample example, @Param("selective") MymallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    List<MymallIssue> selectByExampleSelective(@Param("example") MymallIssueExample example, @Param("selective") MymallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    List<MymallIssue> selectByExample(MymallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    MymallIssue selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallIssue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    MymallIssue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    MymallIssue selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallIssue record, @Param("example") MymallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallIssue record, @Param("example") MymallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallIssue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MymallIssueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_issue
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}