package org.biye.mymall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.biye.mymall.db.domain.MymallPermission;
import org.biye.mymall.db.domain.MymallPermissionExample;

public interface MymallPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    long countByExample(MymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int deleteByExample(MymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int insert(MymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int insertSelective(MymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    MymallPermission selectOneByExample(MymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    MymallPermission selectOneByExampleSelective(@Param("example") MymallPermissionExample example, @Param("selective") MymallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    List<MymallPermission> selectByExampleSelective(@Param("example") MymallPermissionExample example, @Param("selective") MymallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    List<MymallPermission> selectByExample(MymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    MymallPermission selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") MymallPermission.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    MymallPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    MymallPermission selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MymallPermission record, @Param("example") MymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MymallPermission record, @Param("example") MymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MymallPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") MymallPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mymall_permission
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}